
import './globals.css'
import Provider from './context/AuthContext'
import ToasterContext from './context/ToasterContext'
import Navbar from './components/Navbar'
import Footer from './components/footer/Footer'



export const metadata = {
  title: 'NewGen Digital Media',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Provider><ToasterContext /><Navbar />{children}<Footer /></Provider></body>
    </html>
  )
}
